return {
  {
    display_name = "ReaEQ",
    aliases = { "eq", "equalizer", "эквалайзер", "reaeq" },
    type = "effect",
    exact_reaper_fx_name = "ReaEQ (Cockos)",
    format = "VST",
    tags = { "mix", "vocal", "guitar", "drums" },
  },
  {
    display_name = "ReaComp",
    aliases = { "compressor", "comp", "reacomp" },
    type = "effect",
    exact_reaper_fx_name = "ReaComp (Cockos)",
    format = "VST",
    tags = { "mix", "vocal", "drums", "bus" },
  },
  {
    display_name = "ReaGate",
    aliases = { "gate", "noise gate", "reagate" },
    type = "effect",
    exact_reaper_fx_name = "ReaGate (Cockos)",
    format = "VST",
    tags = { "cleanup", "drums", "vocal" },
  },
  {
    display_name = "ReaDelay",
    aliases = { "delay", "echo", "readelay" },
    type = "effect",
    exact_reaper_fx_name = "ReaDelay (Cockos)",
    format = "VST",
    tags = { "delay", "vocal", "fx" },
  },
  {
    display_name = "ReaSynth",
    aliases = { "synth", "instrument", "reasynth" },
    type = "instrument",
    exact_reaper_fx_name = "ReaSynth (Cockos)",
    format = "VST",
    tags = { "synth", "keys", "bass" },
  },
  {
    display_name = "Serum",
    aliases = { "serum", "xfer serum", "сирум" },
    type = "instrument",
    exact_reaper_fx_name = "VST3i: Serum (Xfer Records)",
    format = "VST3",
    tags = { "synth", "bass", "lead", "edm", "phonk" },
    vendor = "Xfer Records",
    category = "instrument",
  },
  {
    display_name = "Omnisphere",
    aliases = { "omnisphere", "spectrasonics omnisphere", "омнисфера", "омнисферу", "омнисферой" },
    type = "instrument",
    exact_reaper_fx_name = "VST3i: Omnisphere (Spectrasonics)",
    format = "VST3",
    tags = { "synth", "pads", "keys", "cinematic", "lead" },
    vendor = "Spectrasonics",
    category = "instrument",
  },
  {
    display_name = "Analog Lab V",
    aliases = { "analog lab", "analog lab v", "arturia analog lab", "arturia analog lab v", "аналог лаб", "артурия аналог лаб" },
    type = "instrument",
    exact_reaper_fx_name = "VST3i: Analog Lab V (Arturia)",
    format = "VST3",
    tags = { "synth", "keys", "pads", "lead" },
    vendor = "Arturia",
    category = "instrument",
  },
  {
    display_name = "ReaSamplOmatic5000",
    aliases = { "sampler", "sample player", "rs5k", "reasamplomatic5000" },
    type = "instrument",
    exact_reaper_fx_name = "ReaSamplOmatic5000 (Cockos)",
    format = "VST",
    tags = { "drums", "sample", "pad" },
  },
  {
    display_name = "ReaControlMIDI",
    aliases = { "midi control", "midi utility", "reacontrolmidi" },
    type = "effect",
    exact_reaper_fx_name = "ReaControlMIDI (Cockos)",
    format = "VST",
    tags = { "midi", "utility" },
  },
}
